# Generated by Django 2.1.5 on 2019-10-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_auto_20191012_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('UNKNOWN', 'Undefined'), ('F', 'Female'), ('M', 'Male')], default='UNKNOWN', max_length=10),
        ),
    ]
